### ISSUE TITLE
Vocab List ​

### ISSUE THREAD

**Issue by ryliecc** [ryliecc/capstone_webdev_wanikani-app#1]
## Value Proposition

**As a** Japanese Language Student  
**I want to** see all available Vocabulary 
**so that** I know which vocabulary is available to me.
​

## Description

![Image](https://github.com/ryliecc/capstone_webdev_wanikani-app/assets/131289679/2ac77a94-b0f3-45b0-84de-665adafa4fe7)

## Acceptance Criteria

- [x] a list is displayed in the App
- [x] the list has the title "Vocabulary"
- [x] the list has three rows for the vocabulary, the reading in 
      Hiragana and the meaning in Romaji
- [x] the list continues until the end when the user scrolls down
      ​

## Tasks

- [x] create a new branch
- [x] create mock-data for the first vocabulary
- [x] create a new Vocab List component
- [x] render Vocab List in App
      ​

**Comment by julialoeschel** [comment]
Hey, great first story. 
I have some minor suggestions: 
- do we need a heading for the list (Hiragana ,Romaji, english)? 
- how does the list behave? (scroll, long entries etc?)
other than that - super cool, nice start!

**Comment by ryliecc** [comment]
> Hey, great first story. I have some minor suggestions:
> 
>     * do we need a heading for the list (Hiragana ,Romaji, english)?
> 
A particular heading for each row is not necessary, because it is clearly visible which kind of alphabet is being used just by looking at it. Vocabulary mixes Kanji with Kana, Hiragana display the reading and Romaji (roman letters) display the meaning. Anyone who studies Japanese knows about these concepts, so I don't think it will be necessary. I added an overall heading though, because I plan to have more than this one list.

>     * how does the list behave? (scroll, long entries etc?)
>       other than that - super cool, nice start!

Added a description for scrolling. :)
