### ISSUE TITLE
Lesson Session

### ISSUE THREAD

**Issue by ryliecc** [ryliecc/capstone_webdev_wanikani-app#12]
## Value Proposition

**As a** Japanese Language Student  
**I want to** enter the Lessons Page 
**so that** I can learn new Kanji
​

## Description

![Image](https://github.com/ryliecc/capstone_webdev_wanikani-app/assets/131289679/c6c13cae-ff75-436c-993a-aa9f4e52dbb8)

## Acceptance Criteria

- [x] clicking Lessons on the Dashboard leads to a new page, the Lessons Session
- [x] at the top of the Lessons Session is a home button that leads back to the dashboard
- [x] shown below is the current lesson item (eg. おはよう) and it's meaning (eg. Good morning)
- [x] below is a bar with two buttons "Meaning" and "Context"
- [x] clicking on one of those buttons opens the according information card
- [x] the default card is "Meaning"
- [x] the "Meaning" card contains sections "Meaning Explanation", "Other Meanings" and "Word Type"
- [x] the "Context" card contains three sections: "Patterns of Use", "Common Word Combinations" and "Context Sentences"
- [x] each "Pattern of Use" section has their own "Common Word Combinations" section that appears when being clicked, the first entry is active by default

## Tasks

- [x] create a new branch
- [x] create Lesson Session page
- [x] create Home Button Component
- [x] created Displayed Item Component
- [x] create Meaning Card Component
- [x] create Context Card Component
- [x] add components to Lesson Session page
      ​

**Comment by CarstenJahnke** [comment]
LGTM, happy hacking! 😊
