### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by ryliecc** [ryliecc/capstone_webdev_wanikani-app#13]
## Value Proposition

**As a** Japanese Language Student  
**I want to** use a styled app 
**so that** I enjoy using it more.
​

## Description

![Image](https://github.com/ryliecc/capstone_webdev_wanikani-app/assets/131289679/4fcb809c-be9d-438d-9e7e-70cb6669eb69)

## Acceptance Criteria

- [x] the five different pages are styled according to the example graphics below
- [x] Radicals, Kanji and Vocabulary use different color themes

## Tasks

- [x] create a new branch
- [x] style components for subject pages
- [x] style components for dashboard
- [x] style components for lesson session
      ​

**Comment by MichanNan** [comment]
LGTM :tada:
