### ISSUE TITLE
US9: Review Session

### ISSUE THREAD

**Issue by ryliecc** [ryliecc/capstone_webdev_wanikani-app#17]
## Value Proposition

**As a** Japanese Language Student  
**I want to** enter a review session 
**so that** I can study all newly learned items.
​

## Description

![Image](https://github.com/ryliecc/capstone_webdev_wanikani-app/assets/131289679/e30dd3b8-f2cd-4eb6-a5d0-8df8508aba1c)

## Acceptance Criteria

- [x] clicking the reviews button on the dashboard leads to a new page
- [x] shown at the top of the page is a colored area, according to the corresponding object type (eg. lilac for vocabulary)
- [x] inside the area is a home button and the review item
- [x] the home button leads back to the dashboard
- [x] following the item area is a bar that shows the specific kind of review (eg. vocabulary reading)
- [x] after comes an input field with a submit button on the right
- [x] entering something into the input field does not do anything yet
- [x] the placeholder text is "答え" (japanese for answer)
- [x] below the input field are four buttons that don't do anything yet

## Tasks

- [x] create a new branch
- [x] create review session page
- [x] link review session page to dashboard
- [x] add home button to page
- [x] create review item area component
- [x] create review category bar component
- [x] create answer form component
- [x] create button component
- [x] render components in review session page
      ​

**Comment by JonasDaJones** [comment]
Very easy to understand. And very detailed. Only issue: you add buttons without functions...

**Comment by ryliecc** [comment]
> Only issue: you add buttons without functions...

As you can see I put in the little word "yet" :) The function of the buttons will be part of another US. This is just the frame for everything. So that was totally intended.
