### ISSUE TITLE
US10: Check answer

### ISSUE THREAD

**Issue by ryliecc** [ryliecc/capstone_webdev_wanikani-app#18]
## Value Proposition

**As a** Japanese Language Student  
**I want to** check my answers 
**so that** I can study effectively.
​

## Description

![Image](https://github.com/ryliecc/capstone_webdev_wanikani-app/assets/131289679/088488f4-11da-41a5-a5d1-af0b9b6638ea)

## Acceptance Criteria

- [x] the input field is focused when entering the review session
- [x] when hitting enter the page shows if the answer was correct
- [x] the input field turns green if the answer is correct
- [x] the input field turns red when the answer is wrong
- [x] additionally a field pops up that suggests clicking the eye button
- [x] when clicking the eye button a field shows up that contains all necessary information
- [x] the field contains four sections: "Meaning", "Reading", "Context" and "Kanji Composition"
- [x] all sections have content that can be toggled by clicking the headline
- [x] the corresponding section to the review item (eg. Reading) is visible by default

## Tasks

- [x] create a new branch
- [x] add input form function
- [x] create information component
- [x] render component in review session page
      ​

**Comment by MichanNan** [comment]
LGTM 🚀
