### ISSUE TITLE
US11: API Token Page

### ISSUE THREAD

**Issue by ryliecc** [ryliecc/capstone_webdev_wanikani-app#19]
## Value Proposition

**As a** Japanese Language Student  
**I want to** connect my WaniKani Account to the app 
**so that** I can have a personalized experience.
​

## Description

![Image](https://github.com/ryliecc/capstone_webdev_wanikani-app/assets/131289679/64b31d99-27a3-46ab-846d-f7efcf952ad9)

## Acceptance Criteria

- [x] if no personal API Token is saved in local storage a new page opens up when opening the app
- [x] the page shows a welcome message and the app header at the top of the page
- [x] a small form is displayed in the center of the page that asks for a personal api token
- [x] below is a textfield that explains how to find your personal token
- [x] the content visibility can be toggled by clicking the headline
- [x] when entering a valid api token to the field and hitting enter the dashboard page appears

## Tasks

- [x] create a new branch
- [x] add welcome page
- [x] create welcome message component
- [x] create input form component
- [x] create loading screen component
- [x] create fetch api data function
- [x] render all components in welcome page
- [x] move dashboard to seperate page
- [x] move welcomepage to app index
- [x] link dashboard to welcome page
      ​

**Comment by rueveydaakuel** [comment]
LGTM 👍
