### ISSUE TITLE
Kanji List

### ISSUE THREAD

**Issue by ryliecc** [ryliecc/capstone_webdev_wanikani-app#2]
## Value Proposition

**As a** Japanese Language Student  
**I want to** see all available Kanji 
**so that** I know which Kanji is available to me.
​

## Description

![Image](https://github.com/ryliecc/capstone_webdev_wanikani-app/assets/131289679/b414c317-ab7e-4169-9766-9b4e8a437f86)

## Acceptance Criteria

- [ ] a list is displayed in the App below the Vocabulary List
- [ ] the list has the title "漢字 - Kanji" 
- [ ] the list has three rows for the Kanji, the reading in 
      Hiragana and the meaning in Romaji
- [ ] the list continues until the end when the user scrolls

## Tasks

- [ ] create a new branch
- [ ] create mock-data for the first Kanji
- [ ] create a new Kanji List component
- [ ] render Kanji List in App
      ​
