### ISSUE TITLE
US12: Display API Data

### ISSUE THREAD

**Issue by ryliecc** [ryliecc/capstone_webdev_wanikani-app#20]
## Value Proposition

**As a** Japanese Language Student  
**I want to** view my personal data in the app 
**so that** I can have a personalized experience.
​

## Description

![Image](https://github.com/ryliecc/capstone_webdev_wanikani-app/assets/131289679/a67a59d5-0054-46a9-a0b2-a303a4a9dd31)

## Acceptance Criteria

- [x] the mock data is replaced with actual data from the API
- [x] the dashboard is updated to show the actual information (eg. Level is below 3 for test users)
- [x] when entering the overview page for radicals you can see all items for the first ten levels instead of just a few from the first two levels
- [x] when entering the overview page for kanji you can see all items for the first ten levels instead of just a few from the first two levels
- [x] when entering the overview page for vocabulary you can see all items for the first ten levels instead of just a few from the first two levels

## Tasks

- [x] create a new branch
- [x] create different fetch functions for data types
- [ ] save data in local storage
- [x] modify components to fit api data

**Comment by matschi3** [comment]
LGTM!
simple US, but i guess its quite some coding to do
