### ISSUE TITLE
US13: Details Pages

### ISSUE THREAD

**Issue by ryliecc** [ryliecc/capstone_webdev_wanikani-app#21]
## Value Proposition

**As a** Japanese Language Student  
**I want to** see more details about the subjects 
**so that** I can study more effectively.
​

## Description

![Image](https://github.com/ryliecc/capstone_webdev_wanikani-app/assets/131289679/405e74da-e3a3-4eeb-a8c2-982a3a27cc80)

## Acceptance Criteria

- [x] when clicking any item on the radicals page a details page opens
- [x] the radical details page contains three sections: "Name", "Found in Kanji" and "Your Progression"
- [x] the heading of the page shows the level number, the radical and its name
- [x] the Kanji are clickable and lead to their corresponding details page
- [x] when clicking any item on the kanji page a details page opens
- [x] the kanji details page contains five sections: "Radical Combination", "Meaning", "Readings", "Found in Vocabulary" and "Your Progression"
- [x] the heading of the page shows the level number, the kanji and its primary meaning
- [x] the Vocabulary items are clickable and lead to their corresponding details page
- [x] when clicking any item on the vocabulary page a details page opens
- [x] the vocab details page contains five sections: "Meaning", "Reading", "Context", "Kanji Composition" and "Your Progression"
- [x] the heading of the page shows the level number, the vocabulary item and its primary meaning
- [x] the kanji are clickable and lead to their corresponding details page

## Tasks

- [x] create a new branch
- [x] create a new details page for radicals
- [x] create components
- [x] render all components inside page
- [x] create onClick function for radical list items
- [x] fill components with corresponding api data
- [x] create a new details page for kanji
- [x] create onClick function for kanji list items
- [x] create components
- [x] render all components inside page
- [x] fill components with corresponding api data
- [x] create a new details page for vocabulary
- [x] create onClick function for vocabulary list items
- [x] create components
- [x] render all components inside page
- [x] fill components with corresponding api data

**Comment by Katemuya** [comment]
Looks good to me. Well detailed 🚀
