### ISSUE TITLE
US14: Several Lesson Items

### ISSUE THREAD

**Issue by ryliecc** [ryliecc/capstone_webdev_wanikani-app#23]
## Value Proposition

**As a** Japanese Language Student  
**I want to** learn new things
**so that** I can add more things to my review pile.
​

## Description

![Image](https://user-images.githubusercontent.com/131289679/250640679-846d12ab-a773-4dab-b878-51cc992ce431.svg)

## Acceptance Criteria

- [x] at the top of the lesson session page is a counter that shows the remaining items for Radicals, Kanji and Vocabulary in this order
- [x] the counter does not change yet, because items will only leave the pile after a successful first quiz
- [x] the nav bar contains two buttons pointing to the left and right side
- [x] at the bottom is a graphic with circles that shows the amount of items until the quiz starts (ergo the session progress)
- [x] when clicking the arrow buttons the page navigates first to the next card (eg. Context) and then to the next lesson item
- [x] after the fifth item nothing happens yet

## Tasks

- [x] create a new branch
- [x] create counter component
- [x] create navigation buttons
- [x] create session progress component
- [x] add all components to the lesson session page
- [x] modify data according to api data

**Comment by dimitriosxmi** [comment]
LGTM nice US I understood the task 😊!
