### ISSUE TITLE
US15: Romaji to Hiragana

### ISSUE THREAD

**Issue by ryliecc** [ryliecc/capstone_webdev_wanikani-app#24]
## Value Proposition

**As a** Japanese Language Student  
**I want to** type in Hiragana without changing my system keyboard
**so that** I can go through reviews more quickly
​

## Description

![Image](https://github.com/ryliecc/capstone_webdev_wanikani-app/assets/131289679/f2395356-209d-4b43-96b1-402587d0dce9)

## Acceptance Criteria

- [x] when typing syllables into the answer field they automatically turn into their corresponding hiragana letter (eg. "ko" -> "こ", "ni" -> "に" and so on)
 

## Tasks

- [x] create a new branch
- [ ] create hiragana chart array
- [x] build function for input field

**Comment by dimitriosxmi** [comment]
## LGTM short and easy to understand User Story!
Notes: great scribbles they illustrate understandably what supposed to happen 😊
