### ISSUE TITLE
US16: Lesson Quiz

### ISSUE THREAD

**Issue by ryliecc** [ryliecc/capstone_webdev_wanikani-app#25]
## Value Proposition

**As a** Japanese Language Student  
**I want to** take quizzes
**so that** I can test my knowledge
​

## Description

![Image](https://github.com/ryliecc/capstone_webdev_wanikani-app/assets/131289679/94e33205-3f7a-49f0-8809-f1e676cdccbc)

## Acceptance Criteria

- [x] on the lesson session page after the fifth item the quiz starts
- [x] the lesson quiz looks similar to the review session
- [ ] a progress bar indicates how far you've come with the quiz
- [x] if answered wrong each item will appear again until it has been answered right
- [x] after finishing the quiz a window pops up asking if you want to continue with lessons or return to the dashboard in case there are still lessons left
 

## Tasks

- [x] create a new branch
- [x] create lesson quiz component
- [ ] create quiz progress bar component
- [x] create functions to modify data
- [x] create continue pop up component
- [x] render everything inside lesson session page

**Comment by dimitriosxmi** [comment]
## LGTM Very nicely described US 🎉
