### ISSUE TITLE
Radicals List

### ISSUE THREAD

**Issue by ryliecc** [ryliecc/capstone_webdev_wanikani-app#3]
## Value Proposition

**As a** Japanese Language Student  
**I want to** see all available Radicals 
**so that** I know which Radical is available to me.
​

## Description

![Image](https://github.com/ryliecc/capstone_webdev_wanikani-app/assets/131289679/6ec0b6d2-4117-467a-a86b-902ebb02cdf9)

## Acceptance Criteria

- [x] a list is displayed in the App below the Kanji List
- [x] the list has the title "部首 - Radicals" 
- [x] the list has two rows for the Radical and the name in Romaji
      ​

## Tasks

- [x] create a new branch
- [x] create mock-data for the first Radicals
- [x] create a new Radical List component
- [x] render Radical List in App
      ​

**Comment by JonasDaJones** [comment]
seems cool for me
