### ISSUE TITLE
List Pages

### ISSUE THREAD

**Issue by ryliecc** [ryliecc/capstone_webdev_wanikani-app#4]
## Value Proposition

**As a** Japanese Language Student  
**I want to** keep every list on a different page 
**so that** I can switch easier between lists.
​

## Description

![Image](https://github.com/ryliecc/capstone_webdev_wanikani-app/assets/131289679/96eab7e3-dba4-4ff1-ba03-91e47ea4e5a5)
![Image](https://github.com/ryliecc/capstone_webdev_wanikani-app/assets/131289679/e2c7f682-01b8-47fc-931d-3da8885d0873)
![Image](https://github.com/ryliecc/capstone_webdev_wanikani-app/assets/131289679/e482efae-f0c9-4f66-b8f3-935304675dac)

## Acceptance Criteria

- [x] every list component has it's own page instead of being displayed after another
      ​

## Tasks

- [x] create a new branch
- [x] create three new pages
- [x] create link to the other pages
- [x] render each list on a different page
      ​

**Comment by ryliecc** [comment]
## Value Proposition

**As a** Japanese Language Student  
**I want to** keep every list on a different page 
**so that** I can switch easier between lists.
​

## Description



![Image](https://github.com/ryliecc/capstone_webdev_wanikani-app/assets/131289679/96eab7e3-dba4-4ff1-ba03-91e47ea4e5a5)
![Image](https://github.com/ryliecc/capstone_webdev_wanikani-app/assets/131289679/e2c7f682-01b8-47fc-931d-3da8885d0873)
![Image](https://github.com/ryliecc/capstone_webdev_wanikani-app/assets/131289679/e482efae-f0c9-4f66-b8f3-935304675dac)



## Acceptance Criteria

- [ ] every list component has it's own page instead of being displayed after another
      ​

## Tasks

- [ ] create a new branch
- [ ] create three new pages
- [ ] render each list on a different page
      ​

**Comment by julialoeschel** [comment]
Think about the navigation: 
dou you need buttons to navigate through the pages?

**Comment by ryliecc** [comment]
> Think about the navigation: do you need buttons to navigate through the pages?

I created a new issue for that because I wasn't sure how much is too much for one single US :)
