### ISSUE TITLE
Navigation Header

### ISSUE THREAD

**Issue by ryliecc** [ryliecc/capstone_webdev_wanikani-app#5]
## Value Proposition

**As a** Japanese Language Student  
**I want to** press buttons to switch between lists
**so that** navigation between pages is possible
​

## Description

![Image](https://github.com/ryliecc/capstone_webdev_wanikani-app/assets/131289679/34770985-6414-4ead-9d02-cfdb9506f87b)

## Acceptance Criteria

- [x] every page has a heading that says "WaniKani"
- [x] below the Heading is a vertical navigation bar with three button
- [x] each button links to the according page
      ​

## Tasks

- [x] create a new branch
- [x] create a header component with a navigation bar
- [x] link each button in the navigation bar to the according page
- [x] render header component at the beginning of each page
      ​

**Comment by CarstenJahnke** [comment]
Clean Work and request implemented directly 👍 Nice 😄
