### ISSUE TITLE
Dashboard Page

### ISSUE THREAD

**Issue by ryliecc** [ryliecc/capstone_webdev_wanikani-app#6]
## Value Proposition

**As a** Japanese Language Student  
**I want to** use a dashboard to navigate through the app
**so that** all important information is visible when launching the app
​

## Description

![Image](https://github.com/ryliecc/capstone_webdev_wanikani-app/assets/131289679/f6ee01a5-72e7-4331-b48e-9f6a38f82837)

## Acceptance Criteria

- [x] at the top of the page is a heading that says "WaniKani"
- [x] below the Heading is a greeting (Ganbatte! = Halte durch! / Gib dein Bestes!)
- [x] below the Greeting are two buttons which show the amount of available item to learn/ review
- [x] the buttons don't link to a specific page yet
- [x] below the lessons and reviews buttons is a bar that shows the level progress
- [x] below the level progress the navigation component from US5 is displayed
- [x] the navigation component links to the according pages

## Tasks

- [x] create a new branch
- [x] create two button components to highlight the necessary information (e.g. numbers of reviews available)
- [x] create level bar component
- [x] create a dashboard page
- [x] render all components inside the dashboard page
- [x] render dashboard page in app
      ​

**Comment by matschi3** [comment]
seems to be good to me.
i like that progress-Bar.
nice Dashboard
